### ISSUE TITLE
What part of SLAM do you use in deep learning?

### ISSUE THREAD

**Issue by hanghoo** [Seanny123/DeepSLAM#1]
Hello,I am a graduate student of The Northeastern University in China. My research is focused on Deep learning for SLAM.I am interested in your research. Could you tell me What part of SLAM do you use in deep learning?

**Comment by Seanny123** [comment]
We just replicated the paper "Replicating Convolutional Neural Network-based Place Recognition"  where a ConvNet is used for feature extraction.

**Comment by hanghoo** [comment]
I got your means. You offer a way to solve the feature extraction. Not application in SLAM problems.
Could you show some your result graph?

**Comment by Seanny123** [comment]
> You offer a way to solve the feature extraction.

Yes, that's all this paper accomplishes.

> Not application in SLAM problems.

It uses this method of feature extraction to help with a SLAM problem, so I'm not sure what you mean here... Does reading [the report my partner and I wrote](https://github.com/Seanny123/DeepSLAM/blob/master/deep-learning-project-final.pdf) help?

**Comment by hanghoo** [comment]
Thank you very much.I will read your report carefully. If I have some problems, I wish I can ask you.
