### ISSUE TITLE
what kind of computer will we need?

### ISSUE THREAD

**Issue by jeannotes** [Seanny123/DeepSLAM#2]
Hi, can I ask you  your computer condition?
some titian X?

**Comment by Seanny123** [comment]
Nah. Anything with a GPU is fine. We were using some sort of GPU that's probably 5 years old at this point.

**Comment by jeannotes** [comment]
Hi, I want to get myself into the slam world, and I also have some experience in deep learning, is your thesis hard to grasp, to what extent may I fully understand?
some lessons or some books to learn?
really need your encourage!!!

**Comment by Seanny123** [comment]
The paper is super simple. If you understand the concept of SLAM and you understand the conv net is just being used as a feature extractor, you already understand the paper.
