### ISSUE TITLE
About Data Files

### ISSUE THREAD

**Issue by Eric-BB** [Seanny123/DeepSLAM#3]
Hello Seanny123:

Thanks for sharing your code ,it's really helpful! Could you share All of the data files? Thanks!

**Comment by Seanny123** [comment]
So, there's a few problems with me sharing the Eynsham dataset used to evaluate this code.

# 1. I don't have permission

The Eynsham dataset was create by Mark Cummins and Paul Newman who are part of the Mobile Robotics Group at the University of Oxford, UK. It used to be hosted on their website, but the link died. I have the files, but there's no license as far as I can tell, so I think I'm supposed to assume full copyright belonging to the authors. Consequently, if you want to email those folks and then let me know if they're okay with me uploading it somewhere, I'd be happy to help. 

# 2. I don't know where to upload it

Even if I were to ignore the copyright issues, the files are 10GB. I don't have a server to host them on and can't use Dropbox or Google Drive or whatever. I could hypothetically upload them to Zenodo, but they apparently won't let you upload folders of files? Do you know where I could upload it?

**Comment by Eric-BB** [comment]
Thank you for your detailed answer.  First, I will  see if there's any other way to get the Eynsham dataset; secondly, could you share some output files?
Thanks for your reply again.

**Comment by Eric-BB** [comment]
Hi, I find you have update the README.md. Wait for your good news!

**Comment by Seanny123** [comment]
The dataset is up! https://zenodo.org/record/1243106
