### ISSUE TITLE
Run Code of DeepSLAM

### ISSUE THREAD

**Issue by ajinkyabedekar** [Seanny123/DeepSLAM#4]
I am working on a research project to replicate a research paper "Learning Deep Representation for Place Recognition in SLAM". The main objective of that paper is that a robot will navigate to different places and check if the place that it is in has been visited earlier by it or not.

I read your report and I found out that your research is somewhat similar to what I am working on. So, can you please let me know which file contains the main code of your research related to what I mentioned above?

Or else, please let me know the steps to run your code of "Convolutional Neural Network-based Place Recognition".

Please let me know as soon as possible

**Comment by Seanny123** [comment]
I wrote this code such a long time ago that I'm not really sure what order to run things in. From what I can tell, I think `timing.py` or ` is the first file to run, because it uses Caffe to generate feature files? Unfortunately, this was before I knew how to structure Python projects properly...
